### ISSUE TITLE
Get Start of Current Quarter

### ISSUE THREAD

**Issue by brendonboshell** [A----/moment-transform#5]
Is it possible to use this plugin to get the start of the quarter for a particular date? I am thinking along the following lines, but I cannot see a way to set the 'month of the quarter' to the start of the quarter. I guess this is a limitation of moment's format() function?

```js
moment().transform('YYYY#+0 1 00:00:00', 'YYYY#Q D HH:mm:ss').format();
```

**Comment by A----** [comment]
You don't need this plugin for that:
```
moment().startOf('quarter').format() // "2017-03-31T00:00:00+XX:YY"
```

**Comment by brendonboshell** [comment]
Okay, perhaps I have misunderstood, but you don't need this plugin for start of year and start of month, yet those are given as [key examples of its use](http://a----.github.io/moment-transform/)?

**Comment by A----** [comment]
Patterns can be user/admin inputs or configuration strings.
